- hosts: webservers                                                                                                                                                 
  become: yes 
  become_user: root
  become_method: sudo
  tasks:
  - name: Include the docker_install role
    include_role:
      name: git
