---

- hosts: webservers                                                                                                                                                 
  become: yes 
  become_user: root
  become_method: sudo
  vars_prompt:

    - name: root_dir
      prompt: Choice the directory to files of website
      private: false
      default: /var/www/html/
      
    - name: cache_st
      prompt: Choise the cache time for static
      private: false
      default: 180h   

    - name: cache_
      prompt: Choice the url to phpadmin panel
      private: false
      default: 127.0.0.1     
         
  tasks:

  - name: generate
    include_role:
      name: template_dock
