---

- hosts: webservers                                                                                                                                                 
  become: yes 
  become_user: root
  become_method: sudo
  vars_prompt:

    - name: file
      prompt: Allow file transfer?
      private: false
      default: "no"
      
    - name: compression
      prompt: Allow gzip compression?
      private: false
      default: "no"   
         
  tasks:

  - name: generate
    include_role:
      name: nginx
