--- 
  - name: off file transfer
    setfact:
      client: "#"
    when: file == "no"  

  - name: on file transfer
    setfact:
      client: ""
    when: file != "no"  

  - name: off gzip
    setfact:
      gzip: "#"
    when: compression == "no"  

  - name: on gzip
    setfact:
      gzip: ""
    when: compression != "no"
  
  - name: Generate nginx.conf
    ansible.builtin.template: 
      src: /home/evgen/ansible/templates/nginx.conf/nginx.conf.j2
      dest: /home/evgen/nginx/nginx.conf
