---

  
  - name: Cat files .js
    ansible.builtin.shell: ls /home/evgen/ansible/templates/proxy-nginx/*.j2
    register: docker
    delegate_to: localhost

  - name: Create the list of src
    ansible.builtin.debug:
      var: docker.stdout_lines  
  
  - name: Generate dockerfiles
    ansible.builtin.template: 
      src: "{{ item }}"
      dest: /home/evgen/"{{ item }}"
    loop: "{{ docker.stdout_lines }}"
      
