---

  
  - name: Cat files .js
    ansible.builtin.shell: ls /home/evgen/ansible/templates/proxy-nginx/*.j2
    register: docker
    delegate_to: localhost

  #- name: Create the list of src
   # set_fact:
    #  list_dock: "{{ docker.stdout_lines.split() }}"    
  
  - name: Generate dockerfiles
    template: 
      src: /home/evgen/ansible/templates/proxy-nginx/"{{ docker.stdout_lines }}"
      dest: /home/evgen/"{{ docker.stdout_lines }}"
    with_items:
      "{{ docker.stdout_lines }}"
      
